runtime: custom
env: flex

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 5

resources:
  cpu: 1
  mem_gb: 1
  disk_size_gb: 10

network:
  session_affinity: true
